### ISSUE TITLE
Load error sqlite

### ISSUE THREAD

**Issue by fluckydog232** [neu-cs6140-summer-2018/assignment-4#1]
hi, I have followed the 'brew' -> 'gem' process but had failure loading the sqlite in my Jupiter notebook.

After sqlite3 install,' require sqlite3' worked in irb, but failed at Notebook . Is this because dependency failure at sqlite against ruby our against ruby notebook.

  | where | Description | env | errorTyp | message
-- | -- | -- | -- | -- | -- 
0.0 | Jpy Notebook | After sqlite3 install, require worked in irb, failed at Notebook | Mac 10.10.2 Notebook Ruby2.4.1  Native ruby version:  ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14] | LoadError | LoadError: cannot load such file -- sqlite3

![image](https://user-images.githubusercontent.com/33081115/41494007-7e7ea298-70c2-11e8-9319-1c2b3d278e9a.png)
![image](https://user-images.githubusercontent.com/33081115/41494009-858de3aa-70c2-11e8-975a-a27e3c20b211.png)

**Comment by abagher2** [comment]
The problem here is that you have installed the gem using sudo, which uses the system-default ruby. Your notebook is running another version of ruby from rbenv. Install sqlite3 in the rbenv hosted ruby.

Note that on the terminal, your message show "Ruby.framework" but in the notebook it shows ".rbenv" Therefore, you have two different versions of ruby.

**Comment by fluckydog232** [comment]
Thanks for confirming my doubt!

**Comment by fluckydog232** [comment]
*[maybe a better way](https://stackoverflow.com/questions/17550903/why-do-i-get-a-permission-denied-error-while-installing-a-gem)
*[rvm](https://rvm.io/rvm/install#explained)
